fix(mirror_base.h): <string.h> replaced by <string>
This was causing a compilation error under linux (with clang):
"mirror_base.h:30:2: error: no type named 'string' in namespace 'std'
plus a lot of dependent errors.